# Generated by demo_img.build_img_prog -- do not hand-edit.
CONFIG m_acc 41200
CONFIG m_cov 41200
IN r
IN g
IN b
IN cr
IN cg
IN cb
IN boost
IN csc
IN cmid
IN amount
IN invone
IN ninth
t0 = MUL(r, cr)
t1 = MUL(g, cg)
t2 = ADD(t0, t1)
t3 = MUL(b, cb)
gray = ADD(t2, t3)
inv = SUB(invone, gray)
br = ADD(gray, boost)
t4 = SUB(gray, cmid)
t5 = MUL(t4, csc)
ct = ADD(t5, cmid)
r00 = SLICE(gray, 0, 0, 286)
b00 = SLICE(r00, 1, 0, 350)
r01 = SLICE(gray, 0, 0, 286)
b01 = SLICE(r01, 1, 1, 351)
r02 = SLICE(gray, 0, 0, 286)
b02 = SLICE(r02, 1, 2, 352)
r10 = SLICE(gray, 0, 1, 287)
b10 = SLICE(r10, 1, 0, 350)
r11 = SLICE(gray, 0, 1, 287)
b11 = SLICE(r11, 1, 1, 351)
r12 = SLICE(gray, 0, 1, 287)
b12 = SLICE(r12, 1, 2, 352)
r20 = SLICE(gray, 0, 2, 288)
b20 = SLICE(r20, 1, 0, 350)
r21 = SLICE(gray, 0, 2, 288)
b21 = SLICE(r21, 1, 1, 351)
r22 = SLICE(gray, 0, 2, 288)
b22 = SLICE(r22, 1, 2, 352)
s0 = ADD(b00, b01)
s1 = ADD(s0, b02)
s2 = ADD(s1, b10)
s3 = ADD(s2, b11)
s4 = ADD(s3, b12)
s5 = ADD(s4, b20)
s6 = ADD(s5, b21)
s7 = ADD(s6, b22)
blur = MUL(s7, ninth)
cr0 = SLICE(gray, 0, 1, 287)
crop = SLICE(cr0, 1, 1, 351)
detail = SUB(crop, blur)
scaled = MUL(amount, detail)
us = ADD(crop, scaled)
strip = CONCAT(crop, blur, 1)
